--I CHANGED THE NAME COLUMN TO UNI NAME FOR EASIER REFERENCE

SELECT *
FROM WORLD_UNI;

--KNOW THE NUMBER OF UNIVERSITIES
SELECT DISTINCT COUNT(UNI_NAME) AS NUM_OF_UNI
FROM WORLD_UNI

--KNOW THE NUMBER OF STUDENT IN EACH UNI(NAME) WITHOUT REPEATING THE UNI NAME
SELECT UNI_NAME, SUM(STUDENT_POPULATION) AS STU_POP
FROM WORLD_UNI
GROUP BY UNI_NAME;

--TOTAL STU POP IN THE UNIVERSITIES
SELECT DISTINCT SUM(STUDENT_POPULATION) AS TOTAL_POP
FROM WORLD_UNI

--KNOW THE VARIOUS COUNTRY FOR EACH UNI
SELECT DISTINCT UNI_NAME, COUNTRY
FROM WORLD_UNI;

--KNOW THE DISTINCT COUNTRIES IN THE DATASET
SELECT DISTINCT COUNTRY
FROM WORLD_UNI;

--KNOW THE DISTINCT NAME OF UNI IN THE DATASET
SELECT DISTINCT UNI_NAME
FROM WORLD_UNI;

--KNOW THE DISTINCT YEARS IN THE DATASET
SELECT DISTINCT YEAR
FROM WORLD_UNI
ORDER BY YEAR ASC;

--MAX STU IN EACH UNI
SELECT UNI_NAME, STUDENT_POPULATION
FROM WORLD_UNI
WHERE STUDENT_POPULATION = (
							SELECT MAX(STUDENT_POPULATION) AS MAX_POP
							FROM WORLD_UNI
						    );

--STUDENT PER YEAR FOR EACH UNI
SELECT UNI_NAME, YEAR, STUDENT_POPULATION
FROM WORLD_UNI
ORDER BY YEAR ASC;


--THE UNI WITH THE HIGHEST F TO M RATIO
SELECT UNI_NAME, FEMALE_TO_MALE_RATIO
FROM WORLD_UNI
WHERE FEMALE_TO_MALE_RATIO =  (
								SELECT MAX(FEMALE_TO_MALE_RATIO) 
								FROM WORLD_UNI
							  );

--KNOW THE UNI WITH THE HIGHEST INTERNATIONAL STUDENT
SELECT UNI_NAME, INTERNATIONAL_STUDENTS
FROM WORLD_UNI
WHERE INTERNATIONAL_STUDENTS LIKE (
								   SELECT MAX(INTERNATIONAL_STUDENTS) AS HIGHEST
								   FROM WORLD_UNI
							    );

--KNOW THE UNI WITH THE HIGHEST STUDENT TO STAFF RATIO
SELECT UNI_NAME, STUDENTS_TO_STAFF_RATIO
FROM WORLD_UNI
WHERE STUDENTS_TO_STAFF_RATIO = (
								 SELECT MAX(STUDENTS_TO_STAFF_RATIO )
								 FROM WORLD_UNI
								 );

--UNI WITH THE HIGHEST OVERALL SCORE
SELECT UNI_NAME, COUNTRY,STUDENT_POPULATION,OVERALL_SCORE
FROM WORLD_UNI
WHERE OVERALL_SCORE = ( 
						SELECT MAX(OVERALL_SCORE)
			            FROM WORLD_UNI
					  );					  
--TOP 5 UNI BASED ON OVERALL SCORE
SELECT TOP 5 uni_name, overall_score
FROM WORLD_UNI
ORDER BY overall_score DESC;


--COMPARE YEAR AND INTERNATIONAL OUTLOOK IN Y 2016
SELECT UNI_NAME,YEAR,INTERNATIONAL_OUTLOOK
FROM WORLD_UNI
WHERE YEAR = '2016';

--KNOW THE TOP 5 UNI IN THE WORLD PER YEAR
SELECT TOP 5 UNI_NAME, YEAR, OVERALL_SCORE
FROM WORLD_UNI
WHERE YEAR IN (2017,2018,2019,2020,2021,2022,2023,2024) AND OVERALL_SCORE > (
						SELECT AVG(OVERALL_SCORE)
			            FROM WORLD_UNI
					  )
ORDER BY UNI_NAME, YEAR;

--KNOW THE TOP 5 UNI IN THE WORLD(BASED ON RESEARCH) PER YEAR
--CAN YOU PLEASE SHARE A VIDEO ON 'RABK' 'OVER' AND 'PARTITION'
WITH RANKED_DATA AS (
  SELECT UNI_NAME, YEAR, OVERALL_SCORE,
         RANK() OVER (PARTITION BY year ORDER BY OVERALL_SCORE DESC) AS RANK
  FROM WORLD_UNI
)
SELECT UNI_NAME, YEAR, OVERALL_SCORE
FROM RANKED_DATA
WHERE RANK <= 5
ORDER BY YEAR, RANK;

--KNOW THE YEAR AND UNI WITH HIGHEST PERFORMANCE 
SELECT UNI_NAME, OVERALL_SCORE, YEAR
FROM WORLD_UNI
WHERE OVERALL_SCORE = ( SELECT MAX(OVERALL_SCORE) AS MAX_SCORE
				    	FROM WORLD_UNI
					  );


--KNOW THE YEAR WITH HIGHEST PERFORMANCE FOR EACH UNI
SELECT UNI_NAME, YEAR, OVERALL_SCORE
FROM (
  SELECT UNI_NAME, YEAR, OVERALL_SCORE,
         RANK() OVER (PARTITION BY UNI_NAME ORDER BY OVERALL_SCORE DESC) AS RANK
  FROM WORLD_UNI
) AS RANKED
WHERE RANK = 1;


--SELECT TOP 10 UNI WITH HIGHEST PERFORMANCE FOR 2024 YEAR
SELECT TOP 10 UNI_NAME, OVERALL_SCORE, YEAR
FROM WORLD_UNI
WHERE YEAR = 2024;

--I REMOVED THE % SIGN SO AS TO RANK PROPERLY
UPDATE WORLD_UNI
SET INTERNATIONAL_STUDENTS = REPLACE(INTERNATIONAL_STUDENTS, '%', '');

SELECT *
FROM WORLD_UNI

--SELECT UNI WITH THE HIGHEST INTERANTIONAL STUDENTS
SELECT TOP 5 UNI_NAME, INTERNATIONAL_STUDENTS
FROM ( SELECT UNI_NAME, INTERNATIONAL_STUDENTS,
       RANK() OVER (ORDER BY INTERNATIONAL_STUDENTS DESC) AS RANK
       FROM WORLD_UNI
	  ) AS RANKED
ORDER BY INTERNATIONAL_STUDENTS DESC;


--COMPARE TEACHING AND OVERALL SCORE IN RELATION TO COUNTRY
SELECT COUNTRY,
       AVG(TEACHING) AS AVG_TEACHING_SCORE,
       AVG(OVERALL_SCORE) AS AVG_OVERALL_SCORE,
	   AVG(OVERALL_SCORE) - AVG(TEACHING) AS SCORE_DIFFERENCE
FROM WORLD_UNI
GROUP BY COUNTRY
ORDER BY SCORE_DIFFERENCE DESC;
